spring:
  application:
    name: schain-service
  profiles:
    active: eureka
server:
  port: 8003
management:
  endpoints:
    web:
      exposure:
        include: '*'
---
eureka:
  client:
    service-url:
      defaultZone: 'http://121.4.31.143:8761/eureka/'
spring:
  config:
    activate:
      on-profile: default

---
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
spring:
  config:
    activate:
      on-profile: localhost
