spring:
  application:
    name: entrance-service
  profiles:
    active: default
server:
  port: 8002
management:
  endpoints:
    web:
      exposure:
        include: '*'
---
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: 'http://121.4.31.143:8761/eureka/'
spring:
  profiles: default

---
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
spring:
  profiles: localhost





