spring:
  application:
    name: entrance-service
  profiles:
    active: default

---
eureka:
  client:
    service-url:
      defaultZone: 'http://gschaos.club:8761/eureka/'
spring:
  profiles: default

---
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
spring:
  profiles: localhost





