spring:
  application:
    name: api-gateway
  profiles:
    active: eureka
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: 'http://gschaos.club:8761/eureka/'
logging:
  level:
    root:
      info
management:
  endpoints:
    web:
      exposure:
        include: '*'

---
spring:
  cloud:
    gateway:
      routes:
        - id: header_route
          uri: http://httpbin.org:80/get
          predicates:
            - Header=X-Request-Id, \d+
  profiles: header_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: cookie_route
          uri: http://httpbin.org:80/get
          predicates:
            - Cookie=name, forezp
  profiles: cookie_route

---
    spring:
      cloud:
        gateway:
          routes:
            - id: host_route
              uri: http://httpbin.org:80/get
              predicates:
                - Host=**.mystical.com
      profiles: host_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: elapse_route
          uri: http://httpbin.org:80/get
          filters:
            - RequestTime=false
          predicates:
            - After=2020-08-20T17:42:47.789-07:00[America/Denver]
  profiles: elapse_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: limit_route
          uri: http://httpbin.org:80/get
          predicates:
            - After=2020-08-20T17:42:47.789-07:00[America/Denver]
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@hostAddrKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 30
  redis:
    host: localhost
    port: 6379
    database: 0
  profiles: limit_route

---
spring:
  cloud:
    discovery:
      enable: true
    loadbalancer:
      retry:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: entrance-service
          uri: lb://entrance-service
          predicates:
            - Path= /entrance/**
            - Method=POST
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-Default-Foo, fws-form-service-Bar
        - id: mystical-stream
          uri: lb://mystical-stream
          predicates:
            - Path= /stream/**
            - Method=POST
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-Default-Foo, fws-form-service-Bar
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path= /auth/**
            - Method=POST
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-Default-Foo, fws-form-service-Bar
  profiles: eureka