server:
  port: 11000

logging:
  level:
    root:
      info
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: 'http://42.192.209.81:8761/eureka/'

---
spring:
  profiles: prod
  application:
    name: gateway
  cloud:
    config:
      uri: http://localhost:3301
      label: main
      profile: prod


---
spring:
  profiles: dev
  application:
    name: gateway
  cloud:
    config:
      uri: http://localhost:3301
      label: main
      profile: dev

---
spring:
  cloud:
    gateway:
      routes:
        - id: header_route
          uri: http://httpbin.org:80/get
          predicates:
            - Header=X-Request-Id, \d+
  profiles: header_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: cookie_route
          uri: http://httpbin.org:80/get
          predicates:
            - Cookie=name, forezp
  profiles: cookie_route

---
    spring:
      cloud:
        gateway:
          routes:
            - id: host_route
              uri: http://httpbin.org:80/get
              predicates:
                - Host=**.mystical.com
      profiles: host_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: elapse_route
          uri: http://httpbin.org:80/get
          filters:
            - RequestTime=false
          predicates:
            - After=2020-08-20T17:42:47.789-07:00[America/Denver]
  profiles: elapse_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: limit_route
          uri: http://httpbin.org:80/get
          predicates:
            - After=2020-08-20T17:42:47.789-07:00[America/Denver]
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@hostAddrKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 30
  redis:
    host: localhost
    port: 6379
    database: 0
  profiles: limit_route
