server:
  port: 8761

eureka:
  instance:
    hostname: 121.4.31.143
    prefer-ip-address: true
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
   application:
     name: eurka-server
