spring:
  application:
    name: auth-service
  profiles:
    active: localhost
  datasource:
    initialization-mode: always
    driverClassName: 'com.mysql.cj.jdbc.Driver'
    url: jdbc:mysql://localhost:3306/mystical?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
server:
  port: 8001
management:
  endpoints:
    web:
      exposure:
        include: '*'
oever:
  signature:
    time-diff-max: 300
    algorithm: HmacSHA1
redis:
  host: localhost
  port: 6379

---
spring:
  profiles: default

---
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
spring:
  profiles: localhost
