spring:
  application:
    name: auth-service
  profiles:
    active: default
  datasource:
    initialization-mode: always
    driverClassName: 'com.mysql.cj.jdbc.Driver'
    url: jdbc:mysql://localhost:3306/mystical?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: '123456'
  rabbitmq:
    host: '121.4.31.143'
    port: 5672
    username: "admin"
    password: "admin"
    # 启动rabbitmq指定的v-host
    virtual-host: my_vhost
secure:
  ignored:
    urls: #安全路径白名单
    - /**/auth/**
    - /**/mq/**

    resources:
    - /static/**
    - /img/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /v2/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /webjars/springfox-swagger-ui/**
server:
  port: 8001
management:
  endpoints:
    web:
      exposure:
        include: '*'
oever:
  signature:
    time-diff-max: 300
    algorithm: HmacSHA1
redis:
  host: localhost
  port: 6379
cookie:
  domain: localhost

---
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: 'http://121.4.31.143:8761/eureka/'
spring:
  profiles: default

---
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
spring:
  profiles: localhost
