spring:
  application:
    name: admin-service
  profiles:
    active: default
server:
  port: 8000
---
eureka:
  client:
    service-url:
      defaultZone: 'http://gschaos.club:8761/eureka/'
    register-with-eureka: false
spring:
  profiles: default

---
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
spring:
  profiles: localhost
