
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        greetings-in:
          destination: greetings
          contentType: application/json
        greetings-out:
          destination: greetings
          contentType: application/json
  application:
    name: mystical-stream
  profiles:
    active: eureka
server:
  port: 8999

---
eureka:
  client:
    service-url:
      defaultZone: 'http://gschaos.club:8761/eureka/'
spring:
  profiles: eureka